apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contacts
spec:
  maxReplicas: 20
  minReplicas: 2
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contacts
