apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: splunk-auto-instrumentation
spec:
  exporter:
    endpoint: http://$(SPLUNK_OTEL_AGENT):4317
  propagators:
    - tracecontext
    - baggage
    - b3
  env:
    - name: SPLUNK_PROFILER_ENABLED
      value: "true"
    - name: SPLUNK_PROFILER_MEMORY_ENABLED
      value: "true"
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
  python:
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-python:0.28b1
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: SPLUNK_OTEL_AGENT
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://$(SPLUNK_OTEL_AGENT):4318/v1/traces
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.28b1
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
  java:
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=splunk-otel-java:v1.32.0
    image: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java:v1.32.0
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
