apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transactionhistory
spec:
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactionhistory
